In [1]:
import torch 

In [24]:
A = torch.rand(6,6)

In [3]:
x = torch.rand(3)

In [4]:
res = torch.mv(A,x)

In [6]:
res

tensor([0.9076, 0.9753, 0.4866])

In [9]:
res.shape

torch.Size([3])

In [26]:
A.view(-1,9)

tensor([[0.1480, 0.5657, 0.0809, 0.8381, 0.8338, 0.6400, 0.2744, 0.6746, 0.9855],
        [0.0955, 0.1086, 0.3696, 0.8708, 0.4986, 0.1080, 0.1836, 0.3376, 0.1627],
        [0.3184, 0.4096, 0.2978, 0.0457, 0.2988, 0.0081, 0.6419, 0.1852, 0.3942],
        [0.1291, 0.5329, 0.1413, 0.8166, 0.7567, 0.4428, 0.5059, 0.1731, 0.4643]])

In [18]:
A

tensor([[0.3217, 0.8939, 0.8835],
        [0.4175, 0.9624, 0.2150],
        [0.4394, 0.1088, 0.1187]])

In [10]:
#First Neural Network

In [ ]:
x = torch.rand()